language: node_js
node_js:
  - '8'
script: npm run lint && npm test
before_deploy: npm run build
deploy:
  provider: npm
  email: 1138148103@qq.com
  skip_cleanup: true
  api_key:
    secure: cc4fb5ff-075b-4be6-af91-b78f38dae300
  on:
    tags: true
    branch: release
  tag: pile-to-str